# Test Loader

This notebook tests the loading of HAR data using the `loader.py` module.

## 1. Module Import

In [1]:
import sys
import numpy as np
from loader import load_har, validate, HARDataset, ACTIVITY_ID_TO_NAME, LOCOMOTION_IDS

print("✓ Import successful!")

✓ Import successful!


## 2. Dataset Loading

In [2]:
# Load complete dataset (train + test merged)
dataset = load_har("data", merge_train_test=True)

print(f"✓ Dataset loaded!")
print(f"  - X shape: {dataset.X.shape}")
print(f"  - y shape: {dataset.y.shape}")
print(f"  - subject_id shape: {dataset.subject_id.shape}")
print(f"  - Number of features: {len(dataset.feature_names)}")

✓ Dataset loaded!
  - X shape: (10299, 561)
  - y shape: (10299,)
  - subject_id shape: (10299,)
  - Number of features: 561


## 3. First Rows Visualization

In [3]:
print("First 5 rows of features:")
print(dataset.X[:5, :5])  # First 5 rows, first 5 columns
print("\nFirst 10 activity labels:")
print(dataset.y[:10])
print("\nFirst 10 subject IDs:")
print(dataset.subject_id[:10])

First 5 rows of features:
[[ 0.28858451 -0.02029417 -0.13290514 -0.9952786  -0.98311061]
 [ 0.27841883 -0.01641057 -0.12352019 -0.99824528 -0.97530022]
 [ 0.27965306 -0.01946716 -0.11346169 -0.99537956 -0.96718701]
 [ 0.27917394 -0.02620065 -0.12328257 -0.99609149 -0.9834027 ]
 [ 0.27662877 -0.01656965 -0.11536185 -0.99813862 -0.98081727]]

First 10 activity labels:
[5 5 5 5 5 5 5 5 5 5]

First 10 subject IDs:
[1 1 1 1 1 1 1 1 1 1]


## 4. Activity Name Property Test

In [4]:
print("First 10 activities by name:")
print(dataset.activity_name[:10])
print("\nAvailable activity mapping:")
for id, name in ACTIVITY_ID_TO_NAME.items():
    print(f"  {id}: {name}")

First 10 activities by name:
['STANDING' 'STANDING' 'STANDING' 'STANDING' 'STANDING' 'STANDING'
 'STANDING' 'STANDING' 'STANDING' 'STANDING']

Available activity mapping:
  1: WALKING
  2: WALKING_UPSTAIRS
  3: WALKING_DOWNSTAIRS
  4: SITTING
  5: STANDING
  6: LAYING


## 5. Dataset Validation

In [5]:
validation_report = validate(dataset)

print("Validation report:")
print("=" * 50)
for key, value in validation_report.items():
    print(f"{key:25s}: {value}")

Validation report:
n_rows                   : 10299
n_features               : 561
n_nan                    : 0
n_inf                    : 0
min_val                  : -1.0
max_val                  : 1.0
n_outside_[-1,1]         : 0
n_subjects               : 30
subject_id_range         : (1, 30)
activity_ids_present     : [1, 2, 3, 4, 5, 6]
class_counts             : {'WALKING': 1722, 'WALKING_UPSTAIRS': 1544, 'WALKING_DOWNSTAIRS': 1406, 'SITTING': 1777, 'STANDING': 1906, 'LAYING': 1944}


## 6. Activity Filtering Test

In [6]:
# Filter only locomotion activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS)
print(f"Locomotion activity IDs: {LOCOMOTION_IDS}")
locomotion_dataset = dataset.filter_activities(LOCOMOTION_IDS)

print(f"\nComplete dataset: {dataset.X.shape[0]} samples")
print(f"Filtered dataset (locomotion only): {locomotion_dataset.X.shape[0]} samples")
print(f"\nActivities present in filtered dataset:")
print(np.unique(locomotion_dataset.activity_name))

Locomotion activity IDs: (1, 2, 3)

Complete dataset: 10299 samples
Filtered dataset (locomotion only): 4672 samples

Activities present in filtered dataset:
['WALKING' 'WALKING_DOWNSTAIRS' 'WALKING_UPSTAIRS']


## 7. Subject Filtering Test

In [7]:
# Filter only first 5 subjects
subset_subjects = [1, 2, 3, 4, 5]
subject_dataset = dataset.filter_subjects(subset_subjects)

print(f"Complete dataset: {dataset.X.shape[0]} samples")
print(f"Filtered dataset (subjects {subset_subjects}): {subject_dataset.X.shape[0]} samples")
print(f"\nSubjects present in filtered dataset:")
print(np.unique(subject_dataset.subject_id))

Complete dataset: 10299 samples
Filtered dataset (subjects [1, 2, 3, 4, 5]): 1609 samples

Subjects present in filtered dataset:
[1 2 3 4 5]


## 8. Combined Test: Activity and Subject Filtering

In [8]:
# Combine filters: only locomotion for first 5 subjects
combined_dataset = dataset.filter_activities(LOCOMOTION_IDS).filter_subjects([1, 2, 3, 4, 5])

print(f"Complete dataset: {dataset.X.shape[0]} samples")
print(f"Dataset with combined filters: {combined_dataset.X.shape[0]} samples")
print(f"\nActivities:")
print(np.unique(combined_dataset.activity_name))
print(f"\nSubjects:")
print(np.unique(combined_dataset.subject_id))

Complete dataset: 10299 samples
Dataset with combined filters: 824 samples

Activities:
['WALKING' 'WALKING_DOWNSTAIRS' 'WALKING_UPSTAIRS']

Subjects:
[1 2 3 4 5]


## 9. Feature Names Visualization

In [9]:
print(f"Total number of features: {len(dataset.feature_names)}")
print("\nFirst 20 features:")
for i, name in enumerate(dataset.feature_names[:20]):
    print(f"  {i+1:3d}. {name}")

Total number of features: 561

First 20 features:
    1. tBodyAcc-mean()-X
    2. tBodyAcc-mean()-Y
    3. tBodyAcc-mean()-Z
    4. tBodyAcc-std()-X
    5. tBodyAcc-std()-Y
    6. tBodyAcc-std()-Z
    7. tBodyAcc-mad()-X
    8. tBodyAcc-mad()-Y
    9. tBodyAcc-mad()-Z
   10. tBodyAcc-max()-X
   11. tBodyAcc-max()-Y
   12. tBodyAcc-max()-Z
   13. tBodyAcc-min()-X
   14. tBodyAcc-min()-Y
   15. tBodyAcc-min()-Z
   16. tBodyAcc-sma()
   17. tBodyAcc-energy()-X
   18. tBodyAcc-energy()-Y
   19. tBodyAcc-energy()-Z
   20. tBodyAcc-iqr()-X


## 10. Class Distribution

In [10]:
print("Class distribution:")
print("=" * 50)
unique_activities, counts = np.unique(dataset.y, return_counts=True)
for activity_id, count in zip(unique_activities, counts):
    activity_name = ACTIVITY_ID_TO_NAME[activity_id]
    percentage = (count / len(dataset.y)) * 100
    print(f"{activity_name:25s}: {count:5d} ({percentage:5.2f}%)")
print("=" * 50)
print(f"{'TOTAL':25s}: {len(dataset.y):5d} (100.00%)")

Class distribution:
WALKING                  :  1722 (16.72%)
WALKING_UPSTAIRS         :  1544 (14.99%)
WALKING_DOWNSTAIRS       :  1406 (13.65%)
SITTING                  :  1777 (17.25%)
STANDING                 :  1906 (18.51%)
LAYING                   :  1944 (18.88%)
TOTAL                    : 10299 (100.00%)


## 11. Subject Distribution

In [11]:
unique_subjects = np.unique(dataset.subject_id)
print(f"Number of subjects: {len(unique_subjects)}")
print(f"Subject ID range: {unique_subjects.min()} - {unique_subjects.max()}")
print("\nSamples per subject:")
for subject_id in sorted(unique_subjects):
    count = (dataset.subject_id == subject_id).sum()
    print(f"  Subject {subject_id:2d}: {count:4d} samples")

Number of subjects: 30
Subject ID range: 1 - 30

Samples per subject:
  Subject  1:  347 samples
  Subject  2:  302 samples
  Subject  3:  341 samples
  Subject  4:  317 samples
  Subject  5:  302 samples
  Subject  6:  325 samples
  Subject  7:  308 samples
  Subject  8:  281 samples
  Subject  9:  288 samples
  Subject 10:  294 samples
  Subject 11:  316 samples
  Subject 12:  320 samples
  Subject 13:  327 samples
  Subject 14:  323 samples
  Subject 15:  328 samples
  Subject 16:  366 samples
  Subject 17:  368 samples
  Subject 18:  364 samples
  Subject 19:  360 samples
  Subject 20:  354 samples
  Subject 21:  408 samples
  Subject 22:  321 samples
  Subject 23:  372 samples
  Subject 24:  381 samples
  Subject 25:  409 samples
  Subject 26:  392 samples
  Subject 27:  376 samples
  Subject 28:  382 samples
  Subject 29:  344 samples
  Subject 30:  383 samples
